version: '3'

services:
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: "nginx"
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - docker-network
    volumes:
      - wordpressdata:/var/www/html/wordpress

  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: "mariadb"
    restart: always
    networks:
      - docker-network
    volumes:
      - mariadbdata:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USER: ${WP_DATABASE_USER}
      WP_DATABASE_PASSWORD: ${WP_DATABASE_PASSWORD}
    # healthcheck:
    #   test: mysql --protocol=tcp -u"$WP_DATABASE_USER" -p"$WP_DATABASE_PASSWORD" -hlocalhost --database="$WP_DATABASE_NAME" -e 'SELECT 1' &> /dev/null
    #   interval: 5s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 10s

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: "wordpress"
    restart: always
    networks:
      - docker-network
    depends_on:
      mariadb
    expose:
      - "9000"
    volumes:
      - wordpressdata:/var/www/html/wordpress
    environment:
      WP_DB_HOST: mariadb
      WP_DB_USER: ${WP_DATABASE_USER}
      WP_DB_PASSWORD: ${WP_DATABASE_PASSWORD}
      WP_DB_NAME: ${WP_DATABASE_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
    # healthcheck:
    #   test: wp core is-installed --allow-root --path=/var/www/html/wordpress &> /dev/null
    #   interval: 5s
    #   timeout: 30s
    #   retries: 10
    #   start_period: 30s

networks:
  docker-network:
    name: docker-network

volumes:
  wordpressdata:
    name: wordpressdata
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/satushi/data/wordpress
  mariadbdata:
    name: mariadbdata
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/satushi/data/mariadb

# condition: service_healthy